# Generated by Django 6.0 on 2026-01-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchers", to="auctions.listing"
            ),
        ),
    ]
