# Generated by Django 6.0 on 2026-01-04 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_user_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
